baseURL: https://piotr-cieslik.github.io/
title: Piotr Cieślik
paginate: 5
defaultContentLanguage: en
theme: PaperMod
googleAnalytics: G-DQ1MYKCYXG
disqusShortname: piotrcieslik

params:
  title: Piotr Cieślik
  homeInfoParams:
    Title: Hi!
    Content:
      I'm Piotr, a software developer from Poland, and I've been writing business applications since 2013.
      My favorite task is simplifying code as much as possible, and even a bit more.
      I enjoy working directly with business people to learn from them, understand their needs, and deliver the best solutions.
      My favorite technologies are .NET Core and React.js. Recently,
      I've been exploring the Microsoft Office 365 and Azure ecosystems to integrate my applications with them.
  socialIcons: # optional
    - name: github
      url: https://github.com/piotr-cieslik
    - name: email
      url: mailto:piotr.cieslik@outlook.com
  ShowBreadCrumbs: true
  comments: true

menu:
  main:
    - name: Search
      url: search/
      weight: 10

# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#search-page
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary